### ISSUE TITLE
Implement AU

### ISSUE THREAD

**Issue by riezebosch** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#11]
Automatic package updates: https://github.com/majkinetor/au

**Comment by jberezanski** [comment]
Good idea. The download page seems fairly stable and easy to parse (unlike the VS 2017 one, for example). I'm not sure I will have the time to do it in the near future, so if you'd like to tackle it, go ahead.

**Comment by riezebosch** [comment]
I did that for [dotnetcore-sdk](https://github.com/riezebosch/BoxstarterPackages/tree/master/dotnetcore-sdk) already.
