### ISSUE TITLE
Install both 64-bit and 32-bit runtimes and package stores on Win64

### ISSUE THREAD

**Issue by jberezanski** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#14]
The hosting bundle does this, so it is probably the right thing to do.

Provide a package parameter for users wanting to opt-out.
Make sure to test on Server Core with WOW64 removed.

**Comment by riezebosch** [comment]
I'd rather stay close to the default behavior and what Microsoft is doing with the installers.

**Comment by jberezanski** [comment]
We already differ from Microsoft in packaging strategy, because we have a single `dotnetcore-runtime.install` package which handles both architectures and Microsoft publishes separate native installers for x64 and x86.

In the one case where Microsoft publishes a single native installer for both architectures (the hosting bundle - `DotNetCore.x.y.z-WindowsHosting.exe`), that installer installs both runtimes and both package stores on a 64-bit OS. That is why I believe my suggestion _would_ bring us closer to what Microsoft is doing.

The change would also align our behavior with that of chocolatey.org packages for other commonly used runtimes:
- [Visual C/C++ Redistributable](https://chocolatey.org/packages/vcredist140) (packages install both bitness runtimes using two native installers)
- [.NET Framework](https://chocolatey.org/packages/dotnetfx) (single native installer which installs both bitness runtimes)

The end result in both cases is that both 32-bit and 64-bit runtimes get installed.

**Comment by riezebosch** [comment]
It *may* align to the windows hosting installer but not to the way the runtime is distributed. The JDK used to install [that way](https://chocolatey.org/packages/jdk8/8.0.141) but has [deprecated it](https://chocolatey.org/packages/jdk8).

**Comment by jberezanski** [comment]
There is currently no way for the user to install both 32 and 64-bit runtimes and have them updated via normal Chocolatey mechanisms.

The JDK is a development kit, not a runtime, so it makes less sense to install both versions. That is why I'm not proposing this for the .NET Core SDK.

**Comment by riezebosch** [comment]
Will accept https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/pull/27 asap.

**Comment by riezebosch** [comment]
It's there, can you wait for the new version to be published or should we publish an update already?
