### ISSUE TITLE
Handle cases when some component versions are not updated in a .NET Core release

### ISSUE THREAD

**Issue by jberezanski** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#31]
Like in #29. The .NET Core 2.0.8 release contained the 2.0.7 runtime, unchanged.

In order to handle such scenarios correctly, AU scripts should parse component versions out of the file names, instead of using the "version-runtime" json property.

**Comment by riezebosch** [comment]
But why?! The property is actually named `version-runtime` so shouldn't we expect it to be the 'version runtime'!

**Comment by jberezanski** [comment]
I thought so too... until 2.0.8 happened. In that release, `version-runtime` = 2.0.8, but _the_ Runtime (as in: dotnet-runtime-X.Y.Z-win-x64.exe) is still 2.0.7 (unchanged from the previous release). This leads to the conclusion that `version-runtime` is something like the version number of the overall release of the runtime components subset of .NET Core (a set consisting of: the actual Runtime, the ASP.NET Core package store and the Windows Server hosting bundle), but individual components in that set do not necessarily need to have the same version.

If we do nothing and Microsoft decides to make another release like this (with non uniform component version numbers), our AU machinery will publish some packages with invalid version (like it happened a few days ago).

**Comment by riezebosch** [comment]
Have you seen the update https://github.com/dotnet/core/issues/1605#issuecomment-393241305?

**Comment by jberezanski** [comment]
Yes, but that comment only tells their plans for 2.0.9, it does not promise "we'll never do this again". This issue is about taking measures to protect our packages from future issues.

**Comment by jberezanski** [comment]
It seems that the versioning format has matured and stabilized, so this is no longer a valid concern.

**Comment by jberezanski** [comment]
...or is it...?

https://github.com/dotnet/core/issues/2139#issuecomment-446631508
> it is possible to have an SDK release which includes previously released runtimes

thankfully
https://github.com/dotnet/core/issues/2134#issuecomment-447069916
> aspnet and net core runtime version version alignment from 2.0 onward will be stable.
