### ISSUE TITLE
Format of releases.json is changing

### ISSUE THREAD

**Issue by martincostello** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#33]
I don't know if you're aware, but I spotted this issue over in the dotnet/core repo:  dotnet/core#1960

It looks like they're going to change the format of the data feed that your scripts use to find new package versions.

**Comment by leecow** [comment]
Thanks Martin. I'll be posting a deprecation announcement as soon as the format is through review. The summary is that we'll continue to update the existing file (v1) for 6 months to give folks ample time to adopt the new format.

**Comment by martincostello** [comment]
Awesome, thanks Lee.

**Comment by martincostello** [comment]
Looks like this was maybe partially resolved by #34, but then might have caused #35.

**Comment by flcdrg** [comment]
Also note that there's now an `sdks` collection - https://github.com/dotnet/core/issues/3114

**Comment by jberezanski** [comment]
The releases.json parsing code seems to be working correctly.
