### ISSUE TITLE
Windows Hosting not being uploaded

### ISSUE THREAD

**Issue by martincostello** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#35]
It looks like the Windows Hosting is not being uploaded anymore by the bot (2.1.6 and 2.2.0 preview 3 are both missing in Chocolatey).

**Comment by riezebosch** [comment]
There are some weird errors on appveyor indeed: https://ci.appveyor.com/project/riezebosch/dotnetcore-chocolateypackages/builds/20303053 I've seen them locally as well but disappeared after subsequent run.

**Comment by martincostello** [comment]
Looks like the script was fixed by your latest change, but things are now out of sync and not being uploaded. Would you be able to do a manual push of the `2.1.6` hosting package please?

**Comment by riezebosch** [comment]
Fixed locally but the problem still occurs on the CI build: https://ci.appveyor.com/project/riezebosch/dotnetcore-chocolateypackages/builds/20311564

**Comment by martincostello** [comment]
I’ve seen issues before where PowerShell has issues with GitHub only supporting TLS 1.2. Could it be something like that maybe?

**Comment by riezebosch** [comment]
It's a bit better again: https://ci.appveyor.com/project/riezebosch/dotnetcore-chocolateypackages/builds/20328984

```
dotnetcore-runtime.install is updated to 2.2.0-preview3 and pushed
```

**Comment by martincostello** [comment]
Great - looks like it skipped over 2.1.6, so I think that just needs a slight manual poke to get added.

**Comment by riezebosch** [comment]
I guess it is because there is a somewhat odd version number published that is considered newer than the current generated.

**Comment by gep13** [comment]
@riezebosch let us know if there is something that we can do to help here.

**Comment by riezebosch** [comment]
I've pushed an update manually. @gep13 Thanks, but I'm afraid the main problem lies in `AU` having some weird behavior.

**Comment by riezebosch** [comment]
Seems like working again: https://ci.appveyor.com/project/riezebosch/dotnetcore-chocolateypackages/builds/20436088 🙌

**Comment by georgechang** [comment]
It looks like `dotnetcore-runtime` 2.1.6 is missing as well causing the `dotnetcore-runtime.install` 2.1.6 to fail because of the dependency.

**Comment by riezebosch** [comment]
Good catch but the dependency is the other way around. `dotnetcore-runtime.install` seems to install fine.

**Comment by georgechang** [comment]
Weird, it must be an issue with upgrading from 2.1.5 to 2.1.6 then. This is what I get when I upgrade `dotnetcore-runtime.install` from 2.1.5 to 2.1.6:

```
Failures
 - dotnetcore-runtime.install (exited 1) - dotnetcore-runtime.install not upgraded. An error occurred during installation:
 Updating 'dotnetcore-runtime.install 2.1.5' to 'dotnetcore-runtime.install 2.1.6' failed. Unable to find a version of 'dotnetcore-runtime' that is compatible with 'dotnetcore-runtime.install 2.1.6'.
```

**Comment by bdukes** [comment]
Did 2.2.3 fail to get uploaded?  I'm getting an error upgrading `aspnetcore-runtimepackagestore` to 2.2.3 because there isn't a 2.2.3 `dotnetcore-windowshosting`
> Updating 'aspnetcore-runtimepackagestore 2.2.2' to 'aspnetcore-runtimepackagestore 2.2.3' failed. Unable to find a version of 'dotnetcore-windowshosting' that is compatible with 'aspnetcore-runtimepackagestore 2.2.3'.

**Comment by riezebosch** [comment]
You're right, the auto update is failing on that package: https://ci.appveyor.com/project/riezebosch/dotnetcore-chocolateypackages#L120
