### ISSUE TITLE
Uninstallation fails for dotnetcore and dotnetcore-runtime packages

### ISSUE THREAD

**Issue by TraGicCode** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#37]
When you perform try to perform a choco uninstall for the `dotnetcore` and `dotnetcore-runtime` packages they just fail.  This is a problem for those wanting to automate this via configuration management tools.

**Comment by riezebosch** [comment]
You're correct, there is no uninstall script. How's your [auto-uninstall](https://chocolatey.org/docs/commands-uninstall) configured?

**Comment by TraGicCode** [comment]
Hey @riezebosch ,

I'm using the stock options for the latest version of chocolatey.  No customizations performed.   Are you able to add an uninstall script for this?

**Comment by TraGicCode** [comment]
Hey @riezebosch ,

Were u able to reproduce this?

**Comment by riezebosch** [comment]
![Screen Shot 2019-05-29 at 23 44 17](https://user-images.githubusercontent.com/1427334/58593625-b289d600-826b-11e9-98c6-0543d9ff4113.png)
 I guess you can call this a repro.

**Comment by riezebosch** [comment]
I'm not sure if my problem was the same, but a `choco upgrade` wouldn't uninstall the old installation first. So when you tried to uninstall later on you'd get the warning stated above. I added a `chocolateybeforemodify.ps` where all current installations are uninstalled first.

**Comment by TraGicCode** [comment]
Hey @riezebosch ,

I will give this a shot.  On a side note would it be possible to get up a seperate package that allows for side-by-side installs?
