### ISSUE TITLE
Need 2.2.106 published

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#41]
Given the issue described in https://github.com/dotnet/announcements/issues/108, I really need the _latest_ SDK that supports VS2017 in the Chocolatey package gallery, that is **2.2.106**

https://dotnet.microsoft.com/download/dotnet-core/2.2

**Comment by riezebosch** [comment]
2.2.107 it is: https://chocolatey.org/packages/dotnetcore-sdk/2.2.107
