### ISSUE TITLE
Support tracking additional SDK versions and use 'sdks' array

### ISSUE THREAD

**Issue by flcdrg** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#43]
There's been some new updates for older SDK versions. It would be good to keep tracking these to ensure older release channels are kept up to date.

The releases.json also now has a 'sdks' array that may contain more recent versions of SDKs too.

**Comment by jberezanski** [comment]
The packages have been making full use of the "sdks" array for nearly a year now.
