### ISSUE TITLE
(dotnetcore-runtime.install) Latest stable version installs pre-release version

### ISSUE THREAD

**Issue by AdmiringWorm** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#47]
The latest version of dotnetcore-runtime.install package (3.1.0) incorrectly installs the latest 3.1.0 preview 3 version instead of the expected stable release.

![image](https://user-images.githubusercontent.com/1474648/70110378-0fb57880-164f-11ea-890b-a57e9856667c.png)

**Comment by AdmiringWorm** [comment]
@riezebosch any chance of getting this corrected?

**Comment by riezebosch** [comment]
Sure thing but I would rather see Microsoft fix it here: https://github.com/dotnet/core/blob/master/release-notes/3.1/releases.json and there is already an issue for that: https://github.com/dotnet/core/issues/3962

**Comment by AdmiringWorm** [comment]
Ah, I was not aware of that issue.
Seems to be just a case of being wrongly labelled then (from what I can tell).

Not a package problem, so nothing to fix then.
Feel free to close the issue, unless you want it to be available when other people navigate to this repo thinking the same as me.

**Comment by riezebosch** [comment]
There [doesn't seem to be a problem](https://github.com/dotnet/core/issues/3962#issuecomment-561913493) except for a cosmetic issue with the label in the installer.
