### ISSUE TITLE
Remove unneeded line

### ISSUE THREAD

**Issue by rgl** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#50]
The line at https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/blob/885690cd41b01a295d09794c37e03ab01c12d306/dotnetcore-windowshosting/Update.ps1#L1 is not really used, can it be removed?

Its not used because its now constructed at https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/blob/885690cd41b01a295d09794c37e03ab01c12d306/dotnetcore-windowshosting/Update.ps1#L20 depending on the channel/stream that is being used.

**Comment by jberezanski** [comment]
Thanks.
