### ISSUE TITLE
Dependency on obsolete? package KB2533623 breaks internalize for dotnetcore-sdk

### ISSUE THREAD

**Issue by OraDotNetDev** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#52]
Hi there,

The [dotnetcore-sdk](https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/tree/master/dotnetcore-sdk) package has a dependency on [KB2533623](https://github.com/jberezanski/ChocolateyPackages/blob/master/KB2533623) which causes the choco internalize process to fail (when using Choco for Business.) 

The Internalize fails, as **all** the required payloads are now unavailable, it appears as though KB2533623 may now been [withdrawn](https://github.com/dotnet/docs/issues/20459). 

As Windows 7 is out of extended support,  a follow up issue [\#5179](https://github.com/dotnet/core/issues/5179) has been raised as to whether DotNet Core still supports it.

Thanks

ODN

```

KB2533623 v1.0.4 [Approved]
Found internalizable Chocolatey functions. Inspecting values for remote resources.
Found 'https://download.microsoft.com/download/D/D/5/DD55423C-2E66-41D3-9815-6B9436B79B6F/Windows6.0-KB2533623-x86.msu' for replacement.
Found 'https://download.microsoft.com/download/9/F/3/9F3EE03C-F0F0-4210-909F-24C1EB9E8AA5/Windows6.0-KB2533623-x64.msu' for replacement.
Found 'https://download.microsoft.com/download/8/9/5/895F11C7-268D-40DD-8266-46A895A4EB09/Windows6.0-KB2533623-x86.msu' for replacement.
Found 'https://download.microsoft.com/download/0/7/7/077825F2-13D0-4209-9C9A-D3F9A49BBCBD/Windows6.0-KB2533623-x64.msu' for replacement.
Found 'https://download.microsoft.com/download/2/D/7/2D78D0DD-2802-41F5-88D6-DC1D559F206D/Windows6.1-KB2533623-x86.msu' for replacement.
Found 'https://download.microsoft.com/download/F/1/0/F106E158-89A1-41E3-A9B5-32FEB2A99A0B/Windows6.1-KB2533623-x64.msu' for replacement.
Found 'https://download.microsoft.com/download/0/B/D/0BD4C49B-92F8-4BD3-A835-8E8A8CDA2A30/Windows6.1-KB2533623-x64.msu' for replacement.
Encountered error downloading package dotnetcore-sdk v:
System.Exception: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.microsoft.com/download/D/D/5/DD55423C-2E66-41D3-9815-6B9436B79B6F/Windows6.0-KB2533623-x86.msu'.
  The remote server returned an error: (404) Not Found...

**Comment by jberezanski** [comment]
I'll probably fix it (soon) on KB2533623 side (since other packages may be affected too), by creating a package for KB4457144 and making KB2533623 redirect to that.

**Comment by jberezanski** [comment]
KB3063858 does the trick and is a very small update (just kernel32.dll, same as KB2533623), while KB4457144 is a full monthly rollup.
KB2533623 [is now a metapackage](https://chocolatey.org/packages/KB2533623/2.0.0), which depends on [KB3063858](https://chocolatey.org/packages/KB3063858/1.0.0).
This works:
- install Win 7 SP1 (e.g. from MSDN)
- manually download and install .NET 4.5 and WMF 5.1
- install Chocolatey
- `cinst -y dotnetcore-runtime.install --source https://myget.org/F/jberezanski-chocolateypackages-dev/api/v2,https://chocolatey.org/api/v2` # will work without my feed once the KB packages pass moderation
- `Restart-Computer`
- `dotnet --list-runtimes` # this would fail without the proper kernel32 update
- `cinst -y dotnetcore-sdk`
- `dotnet new console`
- `dotnet run`

**Comment by jberezanski** [comment]
@OraDotNetDev I have no access to the internalizer, so I cannot test, but I believe it should work now. Please reopen if there still are issues.
