### ISSUE TITLE
.NET 5.0 release

### ISSUE THREAD

**Issue by jamestoyer** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#57]
Hi,

.NET 5.0 has been released now, however the latest 5 version is still a release candidate. It looks to have come out at the same time as 3.1.10, which has been picked up.

Is there any way to get this bumped?

**Comment by jberezanski** [comment]
5.0 is handled by a new set of packages (`dotnet-*`), see [here](https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/issues/45#issuecomment-724858188) for the full list. The 5.0 RC versions on the existing `dotnetcore-*` packages were an interim measure and will be unlisted.
