### ISSUE TITLE
avoid dependencies when not needed

### ISSUE THREAD

**Issue by sl1pkn07** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#59]
Hi

`dotnet-5.0-desktopruntime` pulls unnecesary dependencies when install, for example, in windows 10

`KB2533623` (wich pull a bunch of other unneded dependencies) is not neccesary when use windows 10. please not pull it when install/upgrade the package

this maintain the list of installed packages free of spam/unnecesary packages when the system is aready integrated that dependencies/or not needed

greetings

**Comment by jberezanski** [comment]
These KBs (Windows updates) are needed on older systems and there is no way to specify conditional dependencies in Chocolatey, unfortunately.

**Comment by sl1pkn07** [comment]
https://stackoverflow.com/questions/13688536/how-do-i-specify-conditional-dependencies-based-on-target-framework-in-nuget

this can't work?

greetings

**Comment by jberezanski** [comment]
No. That construct (`<group  targetFramework=".NETFramework4.7.2">`) only applies to real NuGet packages used in software projects. Chocolatey has its roots in NuGet technology (packaging format, communication protocol) but it is ultimately a completely separate world. In particular, the concept of "target framework" has no meaning for Chocolatey and a way to express a dependency on operating system version does not exist yet.

**Comment by jberezanski** [comment]
You're welcome.

However... Once certain old operating systems fall out of support and their usage "in the wild" declines, we can remove old dependencies needed by those operating systems from packages which no longer install on those systems anyway. This could be done as part of #60 .

Closing this issue in favor of the mentioned one.
