### ISSUE TITLE
choco package "dotnet-7.0-sdk-3xx" has issues on validation testing

### ISSUE THREAD

**Issue by ThomasPatzig** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#68]
see
https://community.chocolatey.org/packages/dotnet-7.0-sdk-3xx/

https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0031
https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0061

**Comment by jberezanski** [comment]
Thanks!

**Comment by ThomasPatzig** [comment]
to @jberezanski 
have seen that auto review still report error because of "." in id

https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0061

but what's about all the other packages with same pattern?
https://community.chocolatey.org/packages/dotnet-7.0-sdk-2xx

is this a new rule?
will it be happen for all your packages?
do you have a possibility to reach a real person of choco repo that they can fix there auto reviewer bot / rules?

**Comment by jberezanski** [comment]
cpmr0061 is categorized as a Note, I don't think it will be an issue. Certainly I have no intention of changing the established naming scheme of .NET packages. I've responded in moderation discussion.

However, the validator still reports an issue for the PackageSourceUrl, for some reason. I'll need to investigate.

**Comment by jberezanski** [comment]
I'm not sure what's going on. This time I'm absolutely positive I pushed the correct package, yet the validator still complains. Perhaps a caching issue on chocolatey.org...?

**Comment by jberezanski** [comment]
OK, the validator problem seems to have resolved itself.

**Comment by jberezanski** [comment]
The package is approved now (and already got another version, after this week's Patch Tuesday).
