### ISSUE TITLE
Install 32-bit and 64-bit .NET 6 SDK

### ISSUE THREAD

**Issue by icnocop** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#70]
Hi.

Thank you for dotnet-6.0-sdk.

When I run `choco install dotnet-6.0-sdk`, it seems only the 64-bit version of the SDK is installed.

I expected the 32-bit version of the SDK to also be installed, similar to how the 32-bit and 64-bit .NET 6 runtimes are installed when running `choco install dotnet-6.0-runtime` on a 64-bit operating system.

This is needed, for example, when I want to run `"C:\Program Files (x86)\dotnet\dotnet.exe" test` to run tests specifically targeting 32-bit platform.

Otherwise I get the following error:
```
         The command could not be loaded, possibly because:
           * You intended to execute a .NET application:
               The application 'test' does not exist.
           * You intended to execute a .NET SDK command:
               No .NET SDKs were found.
         
         Download a .NET SDK:
         https://aka.ms/dotnet-download
         
         Learn about SDK resolution:
         https://aka.ms/dotnet/sdk-not-found
```

Thank you.

**Comment by jberezanski** [comment]
That's curious. In my work I've never come across a scenario where the 32-bit SDK would be needed on a 64-bit machine and nobody had ever asked for it either.

> when I want to run "C:\Program Files (x86)\dotnet\dotnet.exe" test to run tests specifically targeting 32-bit platform

The 64-bit SDK should be perfectly capable of running 32-bit tests, provided the 32-bit runtime is installed. Please try running `"C:\Program Files\dotnet\dotnet.exe" test`.

**Comment by icnocop** [comment]
`"C:\Program Files\dotnet\dotnet.exe"` is a 64-bit assembly and since my test assembly is compiled as "Any CPU", the tests will run in a 64-bit process.

This is why I want to run `"C:\Program Files (x86)\dotnet\dotnet.exe"`, since my test assembly is compiled as "Any CPU", to force the tests to run in a 32-bit process.

**Comment by jberezanski** [comment]
In that case you can use the `--arch` or `--runtime` switches to pick a specific runtime. https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test#arguments

**Comment by icnocop** [comment]
Thank you.

`--arch` and `--platform` worked for me which caused `testhost.x86.exe` to run and load my test.

`--runtime` did not work for some reason and displayed the following message:
The following arguments have been ignored : "--runtime win-x86"
